apiVersion: v1
description: 'Postgres-stash by AppsCode - PostgreSQL database backup and restore plugin for Stash'
name: postgres-stash
version: 9.6
appVersion: 9.6
home: https://github.com/stashed/postgres
icon: https://cdn.appscode.com/images/icon/stash.png
sources:
  - https://github.com/stashed/postgres
maintainers:
  - name: appscode
    email: support@appscode.com
