apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: pg-restore-{{- .Chart.Version }}
  labels:
    {{- include "postgres-stash.labels" . | nindent 4 }}
spec:
  steps:
  - name: pg-restore-{{- .Chart.Version }}
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
