apiVersion: v1
description: 'stash-postgres - PostgreSQL database plugin for Stash by AppsCode'
name: stash-postgres
version: v2020.12.17
appVersion: v2020.12.17
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/addons/postgres-stash-addon.png
sources:
- https://github.com/stashed/postgres
maintainers:
- name: appscode
  email: support@appscode.com
