apiVersion: v1
description: 'stash-postgres - PostgreSQL database backup and restore plugin for Stash by AppsCode'
name: stash-postgres
version: "10.2"
appVersion: "10.2"
home: https://github.com/stashed/postgres
icon: https://cdn.appscode.com/images/icon/stash.png
sources:
  - https://github.com/stashed/postgres
maintainers:
  - name: appscode
    email: support@appscode.com
