project:
  name: stash-postgres
  shortName: stash-postgres
  url: https://github.com/stashed/postgres
  description: "PostgreSQL database backup/restore plugin for [Stash by AppsCode](https://stash.run)"
  app: "necessary `Function` and `Task` definition to backup or restore PostgreSQL
    11.2 using Stash"
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: stash-postgres
  version: v2020.08.27-rc.0
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
- Kubernetes 1.11+
release:
  name: stash-postgres-v2020.08.27-rc.0
  namespace: kube-system
