# Default values for stash-postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

image:
  # Docker registry used to pull Postgres addon image
  registry: stashed
  # Docker image used to backup/restore PosegreSQL database
  repository: stash-postgres
  # Tag of the image that is used to backup/restore PostgreSQL database.
  # This is usually same as the database version it can backup.
  tag: "9.6"

backup:
  # Arguments to pass to `pgdump` command  during bakcup process
  args: ""
restore:
  # Arguments to pass to `psql` command during restore process
  args: ""
