# Default values for stash-postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

image:
  # Docker registry used to pull Postgres addon image
  registry: stashed
  # Docker image used to backup/restore PosegreSQL database
  repository: stash-postgres
  # Tag of the image that is used to backup/restore PostgreSQL database.
  # This is usually same as the database version it can backup.
  tag: "11.1"

backup:
  # Postgres dump command, can either be: pg_dumpall  or pg_dump
  cmd: "pg_dumpall"
  # Arguments to pass to `backup.cmd` command during backup process
  args: ""
restore:
  # Arguments to pass to `psql` command during restore process
  args: ""

# Number of seconds to wait for the database to be ready before backup/restore process.
waitTimeout: 300
