apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: postgres-restore-{{- .Chart.Version }}
  labels:
    {{- include "stash-postgres.labels" . | nindent 4 }}
spec:
  image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
  args:
  - restore-pg
  # setup information
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --region=${REPOSITORY_REGION:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret
  - --scratch-dir=/tmp
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0} # 0 indicates use default connection limit
  - --hostname=${HOSTNAME:=}
  - --source-hostname=${SOURCE_HOSTNAME:=}
  - --pg-args=${args:={{ .Values.restore.args }}} # optional arguments pass to pgdump command
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  # target information
  - --namespace=${NAMESPACE:=default}
  - --appbinding=${TARGET_NAME:=}
  - --snapshot=${RESTORE_SNAPSHOTS:=}
  # output & metric information
  - --output-dir=${outputDir:=}
  - --license-apiservice=${LICENSE_APISERVICE:=}
  volumeMounts:
  - name: ${secretVolume}
    mountPath: /etc/repository/secret
